In [3]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [4]:
load_dotenv()

api_key = os.getenv("OPENWEATHER_API_KEY")

In [5]:
url = "https://api.openweathermap.org/data/2.5/weather"

params = {
    "q": "Seoul",
    "appid": api_key,
    "units": "metric"
}

response = requests.get(url, params=params)

In [ ]:
weather = response.json()
weather

{'coord': {'lon': 126.9778, 'lat': 37.5683},
 'weather': [{'id': 803,
   'main': 'Clouds',
   'description': 'broken clouds',
   'icon': '04d'}],
 'base': 'stations',
 'main': {'temp': 28.79,
  'feels_like': 29.06,
  'temp_min': 28.79,
  'temp_max': 28.79,
  'pressure': 1009,
  'humidity': 47,
  'sea_level': 1009,
  'grnd_level': 999},
 'visibility': 10000,
 'wind': {'speed': 4.08, 'deg': 240, 'gust': 3.98},
 'clouds': {'all': 78},
 'dt': 1782971236,
 'sys': {'country': 'KR', 'sunrise': 1782936873, 'sunset': 1782989833},
 'timezone': 32400,
 'id': 1835848,
 'name': 'Seoul',
 'cod': 200}

In [11]:
more_info = {
    "longitude":weather['coord']['lon'],
    "country_code": weather['cod'],
    "cloud_cov_percentage": weather['clouds']['all'],
    "wind_direction": weather['wind']['deg']
}

moreDf = pd.DataFrame([more_info])
more_info

{'longitude': 126.9778,
 'country_code': 200,
 'cloud_cov_percentage': 78,
 'wind_direction': 240}

In [ ]:
record = {
    "city": weather["name"],
    "temperature": weather["main"]["temp"],
    "feels_like": weather["main"]["feels_like"],
    "humidity": weather["main"]["humidity"],
    "pressure": weather["main"]["pressure"],
    "wind_speed": weather["wind"]["speed"],
    "weather": weather["weather"][0]["main"],
    "description": weather["weather"][0]["description"]
}

In [10]:
import pandas as pd

df = pd.DataFrame([record])
df

,city,temperature,feels_like,humidity,pressure,wind_speed,weather,description
0,Seoul,28.79,29.06,47,1009,4.08,Clouds,broken clouds

In [16]:
load_dotenv()
host = os.getenv("DB_HOST")
port = os.getenv("DB_PORT")
database = os.getenv("DB_NAME")
user = os.getenv("DB_USER")
password = os.getenv("DB_PASSWORD")

In [18]:
from sqlalchemy import create_engine

engine = create_engine(
    f"postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}"
)

In [19]:
from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT version();"))
    print(result.fetchone())

('PostgreSQL 17.10 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 15.2.1 20260123 (Red Hat 15.2.1-7), 64-bit',)

In [20]:
df.to_sql(
    "weather",
    engine,
    if_exists="append",
    index=False
)

1

In [21]:
query = "SELECT * FROM weather"

weather_df = pd.read_sql(query, engine)

weather_df

,city,temperature,feels_like,humidity,pressure,wind_speed,weather,description
0,Seoul,28.79,29.06,47,1009,4.08,Clouds,broken clouds

In [ ]:
create_cities_table = """
CREATE TABLE IF NOT EXISTS cities(
    city_id SERIAL PRIMARY KEY,
    city_name VARCHAR(50) NOT NULL,
    country CHAR(2) NOT NULL,
    latitude DECIMAL(8,5),
    longitude DECIMAL(8,5)
);
"""